### ISSUE TITLE
JSON Reference for Devs.

### ISSUE THREAD

**Issue by CorporateDrone** [dataliterate/data-populator#241]
**Which version of the plugin are you using?**
[ ] Data Populator for Sketch
[X] Data Populator for Adobe XD

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to show developers which data points were used in mockups. We have large JSON files. It would be great if there was a way to show developers with JSON key was used in the mockups. We use tools like Zeplin and the native XD Web inspect tools.

**Describe alternatives you've considered**
Manually writing down and annotating in Zeplin or XD Web Inspect tool

**Comment by nitrada** [comment]
@CorporateDrone can you provide more details about the use case – or maybe do a rough visualization of how you imagine this to look like in the plugin UI?
