### ISSUE TITLE
Plugin does not seem to work.

### ISSUE THREAD

**Issue by Buydens** [dataliterate/data-populator#266]
**Which version of the plugin are you using?**
[X ] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Describe the bug**
None of the commands do anything.
There are no windows that appear, no pop-ups... nothing.

**To Reproduce**
1. Go to 'Plugins'
2. Click on 'Data Populator'
3. Click on any of the commands availablele
4. See nothing

**Expected behavior**
For these actions to present windows that allow me to fulfill the action.

**Comment by theguywithhat** [comment]
I have the same issue. As I have worked a lot wit Data Populator before, I feel like this happend with the newest sketch update.

**Comment by rreina** [comment]
I confirm the same issue with Sketch 85.1. This plugin is much more powerful than Sketch built-in data features. It would be awesome if there was a fix.

**Comment by marybmichaels** [comment]
The same is happening to me. It worked for a few days and then stopped.

**Comment by fabianbolte** [comment]
It seems this plugin used an internal class that no longer exists.

Console shows a this:

>standard	12:07:08.428778+0200	Sketch	Possible Unhandled Promise Rejection: ReferenceError: Can't find variable: MSLayerArray at l (/Users/fbolte/Library/Application Support/com.bohemiancoding.sketch3/Plugins/data-populator.sketchplugin/Contents/Sketch/__src_sketch_commands_populateFromURL.js:1:60655) …


From the release notes of Sketch v84:

> We removed the internal class MSLayerArray from our codebase. Code that dealt with layer arrays now uses regular NSArray objects instead. This change made our internal code cleaner and easier to maintain by removing an unnecessary layer of abstraction.
> 
>As mentioned in our [Internal API page](https://developer.sketch.com/plugins/internal-api), this is an internal class that should never be used. But we are aware that some plugins use it, and we’re providing this information to help them migrate their code to use the new APIs.
>
> Code expecting an MSLayerArray object, and using its .layers() method to get an NSArray with the layers, will now receive an NSArray object. The .layers() call is no longer needed.
>
> Plugins relying on any of the internal methods in MSLayerArray will not work. They may even crash Sketch if they’re passing the returned value unchecked to other parts of the plugin code.
> 
> Check the table in the next section for examples of how to migrate your code.
> 
> We recommend using the [JavaScript API](https://developer.sketch.com/plugins/javascript-api) where possible. If you feel something is missing from our API, please [submit feedback and feature requests](https://github.com/sketch-hq/developer.sketch.com/issues)!.

Source: https://developer.sketch.com/plugins/updates/new-in-sketch-84

:-/

**Comment by nitrada** [comment]
@theguywithhat @rreina @marybmichaels @fabianbolte @Buydens we just pushed [a fix](https://www.datapopulator.com/sketch/changelog.html) – please update. sorry for the inconvenience.
